package com.sd.app.bean.company;

// Generated Nov 22, 2014 12:49:05 PM by Hibernate Tools 3.4.0.CR1

/**
 * CompanyTables generated by hbm2java
 */
public class CompanyTables_old implements java.io.Serializable {

	private CompanyTables id;

	public CompanyTables_old() {
	}

	public CompanyTables_old(CompanyTables id) {
		this.id = id;
	}

	public CompanyTables getId() {
		return this.id;
	}

	public void setId(CompanyTables id) {
		this.id = id;
	}

}
