package com.sd.app.bean.company;

// Generated Nov 22, 2014 12:49:05 PM by Hibernate Tools 3.4.0.CR1

/**
 * Company generated by hbm2java
 */
public class Company_old implements java.io.Serializable {

	private Company id;

	public Company_old() {
	}

	public Company_old(Company id) {
		this.id = id;
	}

	public Company getId() {
		return this.id;
	}

	public void setId(Company id) {
		this.id = id;
	}

}
