package com.sd.app.bean.company;

// Generated Nov 22, 2014 12:49:05 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CompanyId generated by hbm2java
 */
@Entity
@Table(name="Company")
public class Company implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -793985338140961498L;
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column
	private Integer compIdNo;
	@Column
	private Integer pcode;
	@Column
	private String initial;
	@Column
	private String name;
	@Column
	private Boolean customer;
	@Column
	private Boolean supplier;
	@Column
	private Boolean glassSupplier;
	@Column
	private String companyClass;
	@Column
	private String type;
	@Column
	private String phonetype1;
	@Column
	private String zone;
	@Column
	private String phone1;
	@Column
	private String phone2;
	@Column
	private String phoneType2;
	@Column
	private String phone3;
	@Column
	private String phone4;
	@Column
	private String phoneType3;
	@Column
	private String phone5;
	@Column
	private String phone6;
	@Column
	private String phoneType4;
	@Column
	private String email1;
	@Column
	private String phoneType5;
	@Column
	private String email2;
	@Column
	private String phoneType6;
	@Column
	private String webSite;
	@Column
	private String address;
	@Column
	private String city;
	@Column
	private String state;
	@Column
	private String pin;
	@Column
	private String crAddress;
	@Column
	private String crCity;
	@Column
	private String crState;
	@Column
	private String crPin;
	@Column
	private String country;
	@Column
	private String dealBy;
	@Column
	private String sdealBy;
	@Column
	private String staxForm;
	@Column
	private String cstNo;
	@Column
	private String lstNo;
	@Column
	private String eccNo;
	@Column
	private String exRegNo;
	@Column
	private String location;
	@Column
	private String fileName;
	@Column
	private String acstatus;
	@Column
	private Integer creditLimit;
	@Column
	private Short creditDays;
	@Column
	private Boolean active;
	@Column
	private Boolean regular;
	@Column
	private Boolean confidential;
	@Column
	private Boolean insurance;
	@Column
	private Boolean intimation;
	@Column
	private Boolean showDiscount;
	@Column
	private Boolean showExcise;
	@Column
	private Date remDate;
	@Column
	private String reminder;
	@Column
	private String notes;
	@Column
	private String supervisorNotes;
	@Column
	private String productionNotes;
	@Column
	private String documentationNotes;
	@Column
	private String printOnInvoice;
	@Column
	private Boolean groupCompany;
	@Column
	private Integer gcode;
	@Column
	private Integer spcode;
	@Column
	private String designation;
	@Column
	private Date entryDate;
	@Column
	private Date modifyDate;
	@Column
	private String freight;
	@Column
	private String supNotes;
	@Column
	private Date supRemDate;
	@Column
	private String supReminder;
	@Column
	private String supRemTime;
	@Column
	private String remTime;
	@Column
	private Boolean newLetter;
	@Column
	private Boolean priceList;
	@Column
	private Boolean diwaliGift;
	@Column
	private Boolean greeting;
	@Column
	private Boolean glassInfo;
	@Column
	private Boolean introduction;
	@Column
	private Boolean tag;
	@Column
	private Boolean printTag;
	@Column
	private Boolean roadPermit;
	@Column
	private String entryBy;
	@Column
	private String modifyBy;


	public Integer getCompIdNo() {
		return this.compIdNo;
	}

	public void setCompIdNo(Integer compIdNo) {
		this.compIdNo = compIdNo;
	}

	public Integer getPcode() {
		return this.pcode;
	}

	public void setPcode(Integer pcode) {
		this.pcode = pcode;
	}

	public String getInitial() {
		return this.initial;
	}

	public void setInitial(String initial) {
		this.initial = initial;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getCustomer() {
		return this.customer;
	}

	public void setCustomer(Boolean customer) {
		this.customer = customer;
	}

	public Boolean getSupplier() {
		return this.supplier;
	}

	public void setSupplier(Boolean supplier) {
		this.supplier = supplier;
	}

	public Boolean getGlassSupplier() {
		return this.glassSupplier;
	}

	public void setGlassSupplier(Boolean glassSupplier) {
		this.glassSupplier = glassSupplier;
	}


	public String getCompanyClass() {
		return companyClass;
	}

	public void setCompanyClass(String companyClass) {
		this.companyClass = companyClass;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getPhonetype1() {
		return this.phonetype1;
	}

	public void setPhonetype1(String phonetype1) {
		this.phonetype1 = phonetype1;
	}

	public String getZone() {
		return this.zone;
	}

	public void setZone(String zone) {
		this.zone = zone;
	}

	public String getPhone1() {
		return this.phone1;
	}

	public void setPhone1(String phone1) {
		this.phone1 = phone1;
	}

	public String getPhone2() {
		return this.phone2;
	}

	public void setPhone2(String phone2) {
		this.phone2 = phone2;
	}

	public String getPhoneType2() {
		return this.phoneType2;
	}

	public void setPhoneType2(String phoneType2) {
		this.phoneType2 = phoneType2;
	}

	public String getPhone3() {
		return this.phone3;
	}

	public void setPhone3(String phone3) {
		this.phone3 = phone3;
	}

	public String getPhone4() {
		return this.phone4;
	}

	public void setPhone4(String phone4) {
		this.phone4 = phone4;
	}

	public String getPhoneType3() {
		return this.phoneType3;
	}

	public void setPhoneType3(String phoneType3) {
		this.phoneType3 = phoneType3;
	}

	public String getPhone5() {
		return this.phone5;
	}

	public void setPhone5(String phone5) {
		this.phone5 = phone5;
	}

	public String getPhone6() {
		return this.phone6;
	}

	public void setPhone6(String phone6) {
		this.phone6 = phone6;
	}

	public String getPhoneType4() {
		return this.phoneType4;
	}

	public void setPhoneType4(String phoneType4) {
		this.phoneType4 = phoneType4;
	}

	public String getEmail1() {
		return this.email1;
	}

	public void setEmail1(String email1) {
		this.email1 = email1;
	}

	public String getPhoneType5() {
		return this.phoneType5;
	}

	public void setPhoneType5(String phoneType5) {
		this.phoneType5 = phoneType5;
	}

	public String getEmail2() {
		return this.email2;
	}

	public void setEmail2(String email2) {
		this.email2 = email2;
	}

	public String getPhoneType6() {
		return this.phoneType6;
	}

	public void setPhoneType6(String phoneType6) {
		this.phoneType6 = phoneType6;
	}

	public String getWebSite() {
		return this.webSite;
	}

	public void setWebSite(String webSite) {
		this.webSite = webSite;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getPin() {
		return this.pin;
	}

	public void setPin(String pin) {
		this.pin = pin;
	}

	public String getCrAddress() {
		return this.crAddress;
	}

	public void setCrAddress(String crAddress) {
		this.crAddress = crAddress;
	}

	public String getCrCity() {
		return this.crCity;
	}

	public void setCrCity(String crCity) {
		this.crCity = crCity;
	}

	public String getCrState() {
		return this.crState;
	}

	public void setCrState(String crState) {
		this.crState = crState;
	}

	public String getCrPin() {
		return this.crPin;
	}

	public void setCrPin(String crPin) {
		this.crPin = crPin;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getDealBy() {
		return this.dealBy;
	}

	public void setDealBy(String dealBy) {
		this.dealBy = dealBy;
	}

	public String getSdealBy() {
		return this.sdealBy;
	}

	public void setSdealBy(String sdealBy) {
		this.sdealBy = sdealBy;
	}

	public String getStaxForm() {
		return this.staxForm;
	}

	public void setStaxForm(String staxForm) {
		this.staxForm = staxForm;
	}

	public String getCstNo() {
		return this.cstNo;
	}

	public void setCstNo(String cstNo) {
		this.cstNo = cstNo;
	}

	public String getLstNo() {
		return this.lstNo;
	}

	public void setLstNo(String lstNo) {
		this.lstNo = lstNo;
	}

	public String getEccNo() {
		return this.eccNo;
	}

	public void setEccNo(String eccNo) {
		this.eccNo = eccNo;
	}

	public String getExRegNo() {
		return this.exRegNo;
	}

	public void setExRegNo(String exRegNo) {
		this.exRegNo = exRegNo;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getAcstatus() {
		return this.acstatus;
	}

	public void setAcstatus(String acstatus) {
		this.acstatus = acstatus;
	}

	public Integer getCreditLimit() {
		return this.creditLimit;
	}

	public void setCreditLimit(Integer creditLimit) {
		this.creditLimit = creditLimit;
	}

	public Short getCreditDays() {
		return this.creditDays;
	}

	public void setCreditDays(Short creditDays) {
		this.creditDays = creditDays;
	}

	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	public Boolean getRegular() {
		return this.regular;
	}

	public void setRegular(Boolean regular) {
		this.regular = regular;
	}

	public Boolean getConfidential() {
		return this.confidential;
	}

	public void setConfidential(Boolean confidential) {
		this.confidential = confidential;
	}

	public Boolean getInsurance() {
		return this.insurance;
	}

	public void setInsurance(Boolean insurance) {
		this.insurance = insurance;
	}

	public Boolean getIntimation() {
		return this.intimation;
	}

	public void setIntimation(Boolean intimation) {
		this.intimation = intimation;
	}

	public Boolean getShowDiscount() {
		return this.showDiscount;
	}

	public void setShowDiscount(Boolean showDiscount) {
		this.showDiscount = showDiscount;
	}

	public Boolean getShowExcise() {
		return this.showExcise;
	}

	public void setShowExcise(Boolean showExcise) {
		this.showExcise = showExcise;
	}

	public Date getRemDate() {
		return this.remDate;
	}

	public void setRemDate(Date remDate) {
		this.remDate = remDate;
	}

	public String getReminder() {
		return this.reminder;
	}

	public void setReminder(String reminder) {
		this.reminder = reminder;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public String getSupervisorNotes() {
		return this.supervisorNotes;
	}

	public void setSupervisorNotes(String supervisorNotes) {
		this.supervisorNotes = supervisorNotes;
	}

	public String getProductionNotes() {
		return this.productionNotes;
	}

	public void setProductionNotes(String productionNotes) {
		this.productionNotes = productionNotes;
	}

	public String getDocumentationNotes() {
		return this.documentationNotes;
	}

	public void setDocumentationNotes(String documentationNotes) {
		this.documentationNotes = documentationNotes;
	}

	public String getPrintOnInvoice() {
		return this.printOnInvoice;
	}

	public void setPrintOnInvoice(String printOnInvoice) {
		this.printOnInvoice = printOnInvoice;
	}

	public Boolean getGroupCompany() {
		return this.groupCompany;
	}

	public void setGroupCompany(Boolean groupCompany) {
		this.groupCompany = groupCompany;
	}

	public Integer getGcode() {
		return this.gcode;
	}

	public void setGcode(Integer gcode) {
		this.gcode = gcode;
	}

	public Integer getSpcode() {
		return this.spcode;
	}

	public void setSpcode(Integer spcode) {
		this.spcode = spcode;
	}

	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	public Date getEntryDate() {
		return this.entryDate;
	}

	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	public String getFreight() {
		return this.freight;
	}

	public void setFreight(String freight) {
		this.freight = freight;
	}

	public String getSupNotes() {
		return this.supNotes;
	}

	public void setSupNotes(String supNotes) {
		this.supNotes = supNotes;
	}

	public Date getSupRemDate() {
		return this.supRemDate;
	}

	public void setSupRemDate(Date supRemDate) {
		this.supRemDate = supRemDate;
	}

	public String getSupReminder() {
		return this.supReminder;
	}

	public void setSupReminder(String supReminder) {
		this.supReminder = supReminder;
	}

	public String getSupRemTime() {
		return this.supRemTime;
	}

	public void setSupRemTime(String supRemTime) {
		this.supRemTime = supRemTime;
	}

	public String getRemTime() {
		return this.remTime;
	}

	public void setRemTime(String remTime) {
		this.remTime = remTime;
	}

	public Boolean getNewLetter() {
		return this.newLetter;
	}

	public void setNewLetter(Boolean newLetter) {
		this.newLetter = newLetter;
	}

	public Boolean getPriceList() {
		return this.priceList;
	}

	public void setPriceList(Boolean priceList) {
		this.priceList = priceList;
	}

	public Boolean getDiwaliGift() {
		return this.diwaliGift;
	}

	public void setDiwaliGift(Boolean diwaliGift) {
		this.diwaliGift = diwaliGift;
	}

	public Boolean getGreeting() {
		return this.greeting;
	}

	public void setGreeting(Boolean greeting) {
		this.greeting = greeting;
	}

	public Boolean getGlassInfo() {
		return this.glassInfo;
	}

	public void setGlassInfo(Boolean glassInfo) {
		this.glassInfo = glassInfo;
	}

	public Boolean getIntroduction() {
		return this.introduction;
	}

	public void setIntroduction(Boolean introduction) {
		this.introduction = introduction;
	}

	public Boolean getTag() {
		return this.tag;
	}

	public void setTag(Boolean tag) {
		this.tag = tag;
	}

	public Boolean getPrintTag() {
		return this.printTag;
	}

	public void setPrintTag(Boolean printTag) {
		this.printTag = printTag;
	}

	public Boolean getRoadPermit() {
		return this.roadPermit;
	}

	public void setRoadPermit(Boolean roadPermit) {
		this.roadPermit = roadPermit;
	}

	public String getEntryBy() {
		return this.entryBy;
	}

	public void setEntryBy(String entryBy) {
		this.entryBy = entryBy;
	}

	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}



}
