package com.sd.app.bean.masters;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated Nov 22, 2014 1:22:06 PM by Hibernate Tools 3.4.0.CR1

/**
 * Units generated by hbm2java
 */
@Entity
@Table(name="Units")
public class Units implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column
	private Integer idNo;
	@Column
	private String coCode;
	@Column
	private String shortName;
	@Column
	private String fullName;
	@Column
	private String city;
	@Column
	private String state;
	@Column
	private String pin;
	@Column
	private String country;
	@Column
	private String phone;
	@Column
	private String fax;
	@Column
	private String email;
	@Column
	private String cstno;
	@Column
	private String webSite;
	@Column
	private String upstno;
	@Column
	private String eccno;
	@Column
	private String exciseRegNo;
	@Column
	private String unitRange;
	@Column
	private String division;
	@Column
	private String unit;
	@Column
	private String address;
	@Column
	private String notificationNo;
	@Column
	private String quotchar;
	@Column
	private String orderChar;
	
	public String getUnitRange() {
		return unitRange;
	}

	public void setUnitRange(String unitRange) {
		this.unitRange = unitRange;
	}

	public String getDivision() {
		return division;
	}

	public void setDivision(String division) {
		this.division = division;
	}

	public String getUnit() {
		return unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getNotificationNo() {
		return notificationNo;
	}

	public void setNotificationNo(String notificationNo) {
		this.notificationNo = notificationNo;
	}

	public String getQuotchar() {
		return quotchar;
	}

	public void setQuotchar(String quotchar) {
		this.quotchar = quotchar;
	}

	public String getOrderChar() {
		return orderChar;
	}

	public void setOrderChar(String orderChar) {
		this.orderChar = orderChar;
	}



	public String getCoCode() {
		return this.coCode;
	}

	public void setCoCode(String coCode) {
		this.coCode = coCode;
	}

	public Integer getIdNo() {
		return this.idNo;
	}

	public void setIdNo(Integer idNo) {
		this.idNo = idNo;
	}

	public String getShortName() {
		return this.shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getPin() {
		return this.pin;
	}

	public void setPin(String pin) {
		this.pin = pin;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getCstno() {
		return this.cstno;
	}

	public void setCstno(String cstno) {
		this.cstno = cstno;
	}

	public String getWebSite() {
		return this.webSite;
	}

	public void setWebSite(String webSite) {
		this.webSite = webSite;
	}

	public String getUpstno() {
		return this.upstno;
	}

	public void setUpstno(String upstno) {
		this.upstno = upstno;
	}

	public String getEccno() {
		return this.eccno;
	}

	public void setEccno(String eccno) {
		this.eccno = eccno;
	}

	public String getExciseRegNo() {
		return this.exciseRegNo;
	}

	public void setExciseRegNo(String exciseRegNo) {
		this.exciseRegNo = exciseRegNo;
	}

}
